name: CI_2
on:
  push:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: |
          pip install pipenv
          pip install mkdocs
      - name: Generate Github Pages
        run: |
          make generate_docs
          git config --global user.name "github-actions[bot]"
          git add -A
          git commit -m "docs: auto generate doc files"
          git push
