name: CI_1
on:
  push:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: pipenv install --dev
      - name: Generate Github Pages
        run: make generate_docs
