name: Generate GithubPages Action
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Generate Github Pages
        run: |
          make generate_mkdocs
          git config --global user.name "github-actions[bot]"
          git add -A
          git commit -m "docs: auto generate doc files"
          git push
